version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install -g yarn
      - yarn install
  build:
    commands:
      - echo Building the project...
      - yarn build
artifacts:
  files:
    - "**/*"
  base-directory: build
cache:
  paths:
    - node_modules/**
