version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install -g yarn
      - yarn install
      - pip install awscli # Cài đặt AWS CLI nếu chưa có
  build:
    commands:
      - echo Building the project...
      - yarn build
  post_build:
    commands:
      - echo Zipping the build folder...
      # - zip -r build.zip build
      - echo Uploading build.zip to S3...
      - aws s3 sync build/ s3://demo-deploy01/deploy/

artifacts:
  files:
    - "**/*"
  base-directory: build
cache:
  paths:
    - node_modules/**
