version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the project...
      - npm run build --verbose
artifacts:
  files:
    - "**/*"
  base-directory: build
cache:
  paths:
    - node_modules/**
