name: Upload source to S3
on:
  push:
    branches:
      - develop
      - staging
      - main

jobs:
  configure-env:
    runs-on: ubuntu-latest
    outputs:  
      environment: ${{ steps.config.outputs.environment }}
    steps:
    - id: config
      name: Config environment base on github branch
      run: |
        if [ "${{ github.ref_name }}" == "develop" ] ; then
            echo "env=dev" >> "$GITHUB_OUTPUT"
            echo "environment=develop" >> "$GITHUB_OUTPUT"
            echo "s3_source_code_path=${{ secrets.DEV_S3_SOURCE_CODE_BATCH }}" >> "$GITHUB_OUTPUT"
        elif [ "${{ github.ref_name }}" == "staging" ] ; then
            echo "env=stg" >> "$GITHUB_OUTPUT"
            echo "environment=staging" >> "$GITHUB_OUTPUT"
            echo "s3_source_code_path=${{ secrets.STG_S3_SOURCE_CODE_BATCH }}" >> "$GITHUB_OUTPUT"
        elif [ "${{ github.ref_name }}" == "main" ] ; then
            echo "env=main" >> "$GITHUB_OUTPUT"
            echo "environment=production" >> "$GITHUB_OUTPUT"
            echo "s3_source_code_path=${{ secrets.PROD_S3_SOURCE_CODE_BATCH }}" >> "$GITHUB_OUTPUT"
        else
            echo "no flag"
        fi
  upload-to-s3:
    runs-on: ubuntu-latest
    needs: configure-env
    environment:  ${{ needs.configure-env.outputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Print environment
        run: echo "Environment is ${{ needs.configure-env.outputs.environment }}"
      - name: print env
        run: echo "Env is ${{ PROD_S3_SOURCE_CODE_BATCH }}"
      - name: print s3 path
        run: echo "S3 path is ${{ needs.configure-env.outputs.s3_source_code_path }}"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install zip
        run: sudo apt-get install zip
      - name: zip code
        run: |
            zip -r secrets.ZIP_FILE . 
      - name: Configure AWS to use OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: us-east-1
      - name: Upload to S3
        run: |
          aws s3 cp ${{ secrets.ZIP_FILE }} s3://${{ needs.configure-env.outputs.s3_source_code_path }}/