name: Upload source to S3
on:
  push:
    branches:
      - develop
      - staging
      - main

jobs:
  configure-env:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
      s3_path: ${{ steps.set-env.outputs.s3_source_code_path }}
    steps:
      - id: set-env
        name: Configure environment and S3 path based on branch
        run: |
          case "${{ github.ref_name }}" in
            develop)
              echo "environment=develop" >> $GITHUB_OUTPUT
              echo "s3_source_code_path=${{ secrets.DEV_S3_SOURCE_CODE_BATCH }}" >> $GITHUB_OUTPUT
              ;;
            staging)
              echo "environment=staging" >> $GITHUB_OUTPUT
              echo "s3_source_code_path=${{ secrets.STG_S3_SOURCE_CODE_BATCH }}" >> $GITHUB_OUTPUT
              ;;
            main)
              echo "environment=production" >> $GITHUB_OUTPUT
              echo "s3_source_code_path=${{ secrets.PROD_S3_SOURCE_CODE_BATCH }}" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "Invalid branch. Exiting."
              exit 1
              ;;
          esac

  upload-to-s3:
    runs-on: ubuntu-latest
    needs: configure-env
    environment: ${{ needs.configure-env.outputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Print environment
        run: |
          echo "Environment: ${{ needs.configure-env.outputs.environment }}"
          echo "S3 Path: ${{ needs.configure-env.outputs.s3_path }}"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install zip
        run: sudo apt-get install -y zip
      - name: Zip code
        run: zip -r poster-backend2.zip .
      - name: Configure AWS to use OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: us-east-1
      - name: Upload to S3
        run: |
          aws s3 cp poster-backend2.zip s3://${{ needs.configure-env.outputs.s3_path }}
