name: Sync to CodeCommit

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
           fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure Git to use AWS CodeCommit credential helper
        run: |
          git config --global credential.helper '!aws codecommit credential-helper $@'
          git config --global credential.UseHttpPath true

      - name: remote git
        run: |
          git remote add codecommit https://git-codecommit.${{ secrets.AWS_REGION }}.amazonaws.com/v1/repos/demo-deploy
      # - name: Fetch and rebase before push
      #   run: |
      #     git fetch codecommit ${{ secrets.GIT_BRANCH }}
      #     git rebase codecommit/${{ secrets.GIT_BRANCH }}

      - name: Sync to CodeCommit
        run: |
          git push -u codecommit ${{ secrets.GIT_BRANCH }} --force-with-lease
