name: Upload source to S3
on:
  push:
    branches:
      - develop
      - staging
      - main
jobs:
  configure-env:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.config.outputs.environment }}
    steps:
      - id: config
        name: Config environment base on github branch
        run: |
          if [ "${{ github.ref_name }}" == "develop" ] ; then
              echo "env=dev" >> "$GITHUB_OUTPUT"
              echo "environment=develop" >> "$GITHUB_OUTPUT"
          elif [ "${{ github.ref_name }}" == "staging" ] ; then
              echo "env=stg" >> "$GITHUB_OUTPUT"
              echo "environment=staging" >> "$GITHUB_OUTPUT"
          elif [ "${{ github.ref_name }}" == "main" ] ; then
              echo "env=main" >> "$GITHUB_OUTPUT"
              echo "environment=production" >> "$GITHUB_OUTPUT"
          else
              echo "no flag"
          fi
  upload-to-s3:
    runs-on: ubuntu-latest
    needs: configure-env
    environment: ${{ needs.configure-env.outputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Print environment
        run: echo "Environment is ${{ needs.configure-env.outputs.environment }}"
      - name: Checkout code
        uses: actions/checkout@v4
      # - id: slack
      #   uses: slackapi/slack-github-action@v1.25.0
      #   with:
      #     channel-id: "${{ secrets.SLACK_CHANNEL }}"
      #     payload: |
      #       {
      #         "text": "<!channel>\nDeployment for Batch started",
      #         "attachments": [
      #           {
      #             "pretext": "ENV: ${{ needs.configure-env.outputs.environment }}\nRepository: ${{ github.repository }}\nGitHub Action uploads code to S3\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
      #             "color": "dbab09"
      #           }
      #         ]
      #       }
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
      # - name: Install zip
      #   run: sudo apt-get install zip
      # - name: zip code
      #   run: |
      #     zip -r ${{ secrets.ZIP_FILE }} .
      - name: Configure AWS to use OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::423623843665:role/github_action_cicd_role
          aws-region: ap-northeast-1
      # - name: Upload to S3
      #   run: |
      #     aws s3 cp ${{ secrets.ZIP_FILE }} s3://${{ secrets.S3_SOURCE_CODE_PATH }}/
      # - name: Report Status
      #   if: failure()
      #   uses: slackapi/slack-github-action@v1.25.0
      #   with:
      #     channel-id: "${{ secrets.SLACK_CHANNEL }}"
      #     payload: |
      #       {
      #         "text": "<!channel>\nDeployment for Batch Failure :error:",
      #         "attachments": [
      #           {
      #             "pretext": "ENV: ${{ needs.configure-env.outputs.environment }}\nRepository: ${{ github.repository }}\nGitHub Action uploads code to S3 result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
      #             "color": "ff0000"
      #           }
      #         ]
      #       }
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
