name: Upload source to S3
on:
  push:
    branches:
      - develop
      - staging
      - main

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Determine environment and S3 bucket
        id: set-env
        run: |
          case "${{ github.ref_name }}" in
            develop)
              echo "environment=develop" >> $GITHUB_ENV
              echo "s3_bucket=${{ secrets.DEV_S3_SOURCE_CODE_BATCH }}" >> $GITHUB_ENV
              ;;
            staging)
              echo "environment=staging" >> $GITHUB_ENV
              echo "s3_bucket=${{ secrets.STG_S3_SOURCE_CODE_BATCH }}" >> $GITHUB_ENV
              ;;
            main)
              echo "environment=production" >> $GITHUB_ENV
              echo "s3_bucket=${{ secrets.PROD_S3_SOURCE_CODE_BATCH }}" >> $GITHUB_ENV
              ;;
            *)
              echo "Invalid branch. Exiting."
              exit 1
              ;;
          esac
      - name: Print environment and S3 bucket
        run: |
          echo "Environment: ${{ env.environment }}"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install zip
        run: |
          sudo apt-get install -y zip
      - name: Zip code
        run: |
          zip -r ${{ secrets.ZIP_FILE }} .
      - name: Configure AWS to use OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: us-east-1
      - name: Upload to S3
        run: |
          aws s3 cp ${{ secrets.ZIP_FILE }} s3://${{ env.s3_bucket }}
