name: Sync to CodeCommit

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::423623843665:role/github_action_cicd_role
          aws-region: ap-northeast-1
      - name: Install zip
        run: sudo apt-get install zip
      - name: zip code
        run: |
          zip -r poster-ai-backend.zip .
      - name: Upload to S3
        run: aws s3 cp poster-ai-backend.zip s3://aillio-dev-source-code/demo/
      # - name: Configure Git to use AWS CodeCommit credential helper
      #   run: |
      #     git config --global credential.helper '!aws codecommit credential-helper $@'
      #     git config --global credential.UseHttpPath true

      # - name: remote git
      #   run: |
      #     git remote add codecommit https://git-codecommit.${{ secrets.AWS_REGION }}.amazonaws.com/v1/repos/${{ secrets.GIT_REPO }}

      # - name: Sync to CodeCommit
      #   run: |
      #     git push -u codecommit ${{ secrets.GIT_BRANCH }} --force
